import alliancesCall from "./calls/alliancesCall";
import loanHistoryCall from "./calls/loanHistoryCall";
import nationCall from "./calls/nationCall";
import nationsCall from "./calls/nationsCall";
import projectsCall from "./calls/projectsCall";
import memberContributionsCall from "./calls/membersContributionsCall";
import memberTechCall from "./calls/memberTechCall";
import memberMilitaryCall from "./calls/memberMilitaryCall";
import memberEffectsCall from "./calls/memberEffectsCall";
import allianceLoanHistoryCall from "./calls/allianceLoanHistoryCall";
import allianceBankHistoryCall from "./calls/allianceBankHistoryCall";
import allianceGrantHistoryCall from "./calls/allianceGrantHistoryCall";
import allianceEquipmentTransactionHistoryCall from "./calls/allianceEquipmentTransactionHistoryCall";
import allianceEquipmentCall from "./calls/allianceEquipmentCall";
import allianceBankCall from "./calls/allianceBankCall";
import allianceTaxIncomeCall from "./calls/allianceTaxIncomeCall";
import allianceApplicationsCall from "./calls/allianceApplicationsCall";
import allianceGrantRequestCall from "./calls/allianceGrantRequestCall";
import allianceLoanRequestCall from "./calls/allianceLoanRequestCall";
import memberBankHistoryCall from "./calls/memberBankHistoryCall";
import memberEquipmentTransactionHistoryCall from "./calls/memberEquipmentTransactionHistoryCall";
import memberTradeHistoryCall from "./calls/memberTradeHistoryCall";
import memberBuildingsCall from "./calls/memberBuildingCall";
import memberPolicyLastRan from "./calls/memberPolicyLastRanCall";
import memberContributionCall from "./calls/memberContributionsCall";
import memberDepositsCall from "./calls/memberDepositsCall";
import memberInventoryCall from "./calls/memberInventoryCall";
import memberFundsCall from "./calls/memberFundsCall";
import nationWarHistoryCall from "./calls/nationWarHistoryCall";
import nationWarActionHistoryCall from "./calls/nationWarActionHistoryCall";
import allianceWarHistoryCall from "./calls/allianceWarHistoryCall";

export default class DnsAPI {
    nationCall = nationCall;
    nationsCall = nationsCall;
    projectsCall = projectsCall;
    loanHistoryCall = loanHistoryCall;
    alliancesCall = alliancesCall;
    memberContributionsCall= memberContributionsCall;
    memberTechCall = memberTechCall;
    memberMilitaryCall = memberMilitaryCall;
    memberEffectsCall = memberEffectsCall;
    allianceBankHistoryCall = allianceBankHistoryCall;
    allianceGrantHistoryCall = allianceGrantHistoryCall;
    allianceLoanHistoryCall = allianceLoanHistoryCall;
    allianceEquipmentTransactionHistoryCall = allianceEquipmentTransactionHistoryCall;
    allianceEquipmentCall = allianceEquipmentCall;
    allianceBankCall = allianceBankCall;
    allianceTaxIncomeCall = allianceTaxIncomeCall;
    allianceApplicationsCall = allianceApplicationsCall;
    allianceGrantRequestCall = allianceGrantRequestCall;
    allianceLoanRequestCall = allianceLoanRequestCall;
    memberBankHistoryCall = memberBankHistoryCall;
    memberEquipmentTransactionHistoryCall = memberEquipmentTransactionHistoryCall;
    memberTradeHistoryCall = memberTradeHistoryCall;
    memberBuildingsCall = memberBuildingsCall;
    memberPolicyLastRan = memberPolicyLastRan;
    memberContributionCall = memberContributionCall;
    memberDepositsCall = memberDepositsCall;
    memberInventoryCall = memberInventoryCall;
    memberFundsCall = memberFundsCall;
    nationWarHistoryCall = nationWarHistoryCall;
    nationWarActionHistoryCall = nationWarActionHistoryCall;
    allianceWarHistoryCall = allianceWarHistoryCall;
}