export interface AllianceBank {
    AllianceCash: number,
    AllianceMinerals: number, 
    AllianceTech: number,    
    AllianceUranium: number,   
    AllianceRareMetal: number,  
    AllianceFuel: number,    
    AllianceBankCash: number,
    AllianceBankMinerals: number,
    AllianceBankTech: number,
    AllianceBankUranium: number,
    AllianceBankRareMetal: number,
    AllianceBankFuel: number,
    AllianceBankCashOwed: number,
    AllianceBankMineralsOwed: number,
    AllianceBankTechOwed: number,
    AllianceBankUraniumOwed: number,
    AllianceBankRareMetalOwed: number,
    AllianceBankFuelOwed: number
}