export interface Alliance {
    AllianceId: number,
    AllianceName: string,
    LeaderName: string,
    MemberCount: number,
    CreationDate: Date,
    Score: number,
    AllianceIncome: number,
    AllianceMineralIncome: number,
    AllianceUraniumIncome: number,
    AllianceProductionIncome: number,
    AllianceRareMetalIncome: number,
    TotalLand: number,
    TotalPopulation: number,
    TotalProjects: number,
    AverageWarIndex: number,
    AverageStabilityIndex: number,
    AverageTechIndex: number,
    AverageEducationIndex: number,
    AverageCommerceIndex: number,
    AverageEmploymentIndex: number,
    AveragePowerIndex: number,
    TotalWarVictorys: number,
    TotalWarDefeats: number,
    AverageTransportationIndex: number,
    AllianceFuelIncome: number,
    AllianceTechIncome: number,
}