export interface LoanHistory {
    LoanId: number,
    GiverId: number,
    ReciverId: number,
    ReciverName: string,
    GiverName: string,
    GiverType: number,
    ReciverType: number,
    LoanType: string,
    LoanResourceType: string,
    InitialAmount: number,
    UpfrontFee: number,
    InterestRate: number,
    ForcedInterest: number,
    MinimumPayment: number,
    PaymentDurationType: string,
    PaymentDuration: number,
    RequestText: string,
    GivenDate: Date,
    NextPaymentDueDate: Date,
    DueDate: Date,
    NextInterestDate: Date,
    PercentRepayed: number,
    MissedPaymentsInARow: number,
    MissedPayments: number,
    LoanStatus: string,
    Late: number,
    SoldOff: number,
    FrozenInterest: number,
    CurrentAmount: number,
    TotalPayedAmount: number,
    TotalInterest: number,
    ApprovalText: ' ',
    RemainingMinimumPayment: number,
    DebtCollectedDate: null,
    PayedOffDate: Date,
    InterestType: string
}