export interface MemberContribution {
    nationName: string,
    memberId: number,
    NetCashContribution: number,
    NetMineralContribution: number,
    NetTechContribution: number,
    NetUraniumContribution: number,
    NetRareMetalContribution: number,
    NetFuelContribution: number,
    CashContribution: number,
    MineralContribution: number,
    TechContribution: number,
    UraniumContribution: number,
    RareMetalContribution: number,
    FuelContribution: number,
    CashReceived: number,
    MineralReceived: number,
    TechReceived: number,
    UraniumReceived: number,
    RareMetalReceived: number,
    FuelReceived: number
}